//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pytocs.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pytocs.Core.Resources2", typeof(Resources2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - modules loaded: {0}.
        /// </summary>
        internal static string AnalysisModulesLoaded {
            get {
                return ResourceManager.GetString("AnalysisModulesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - number of definitions: {0}.
        /// </summary>
        internal static string AnalysisNumberDefinitions {
            get {
                return ResourceManager.GetString("AnalysisNumberDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - number of references: {0}.
        /// </summary>
        internal static string AnalysisNumberReferences {
            get {
                return ResourceManager.GetString("AnalysisNumberReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - name resolve rate: {0}.
        /// </summary>
        internal static string AnalysisNumberResolutionPercentage {
            get {
                return ResourceManager.GetString("AnalysisNumberResolutionPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - resolved names: {0}.
        /// </summary>
        internal static string AnalysisNumberResolvedNames {
            get {
                return ResourceManager.GetString("AnalysisNumberResolvedNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - unresolved names: {0}.
        /// </summary>
        internal static string AnalysisNumberUnresolvedNames {
            get {
                return ResourceManager.GetString("AnalysisNumberUnresolvedNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - number of cross references: {0}.
        /// </summary>
        internal static string AnalysisNumberXrefs {
            get {
                return ResourceManager.GetString("AnalysisNumberXrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - failed to parse: {0}.
        /// </summary>
        internal static string AnalysisParseFailures {
            get {
                return ResourceManager.GetString("AnalysisParseFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - semantic problems: {0}.
        /// </summary>
        internal static string AnalysisSemanticProblems {
            get {
                return ResourceManager.GetString("AnalysisSemanticProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis symmary.
        /// </summary>
        internal static string AnalysisSummary {
            get {
                return ResourceManager.GetString("AnalysisSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - total time: {0}.
        /// </summary>
        internal static string AnalysisTotalTime {
            get {
                return ResourceManager.GetString("AnalysisTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing uncalled functions..
        /// </summary>
        internal static string AnalyzingUncalledFunctions {
            get {
                return ResourceManager.GetString("AnalyzingUncalledFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AST cache is at: {0}.
        /// </summary>
        internal static string AstCacheIsAt {
            get {
                return ResourceManager.GetString("AstCacheIsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected at least one except clause or a finally clause..
        /// </summary>
        internal static string ErrExpectedAtLeastOneExceptClause {
            get {
                return ResourceManager.GetString("ErrExpectedAtLeastOneExceptClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected function or class definition, but saw {0}..
        /// </summary>
        internal static string ErrExpectedFunctionOrClassDefinition {
            get {
                return ResourceManager.GetString("ErrExpectedFunctionOrClassDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a ModuleType..
        /// </summary>
        internal static string ErrExpectedModuleType {
            get {
                return ResourceManager.GetString("ErrExpectedModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected token type {0} but saw {1}..
        /// </summary>
        internal static string ErrExpectedTokenButSaw {
            get {
                return ResourceManager.GetString("ErrExpectedTokenButSaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create tmp directory {0}..
        /// </summary>
        internal static string ErrFailedToCreateTmpDirectory {
            get {
                return ResourceManager.GetString("ErrFailedToCreateTmpDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character &apos;{0}&apos; (U+{1:X4})..
        /// </summary>
        internal static string ErrInvalidCharacter {
            get {
                return ResourceManager.GetString("ErrInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hexadecimal string {0}..
        /// </summary>
        internal static string ErrInvalidHexadecimalString {
            get {
                return ResourceManager.GetString("ErrInvalidHexadecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one keyword argument specifier..
        /// </summary>
        internal static string ErrMoreThanOneKwargs {
            get {
                return ResourceManager.GetString("ErrMoreThanOneKwargs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one positional argument specifier..
        /// </summary>
        internal static string ErrMoreThanOneStargs {
            get {
                return ResourceManager.GetString("ErrMoreThanOneStargs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of input..
        /// </summary>
        internal static string ErrUnexpectedEndOfInput {
            get {
                return ResourceManager.GetString("ErrUnexpectedEndOfInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of string constant..
        /// </summary>
        internal static string ErrUnexpectedEndOfStringConstant {
            get {
                return ResourceManager.GetString("ErrUnexpectedEndOfStringConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token {0}..
        /// </summary>
        internal static string ErrUnexpectedToken {
            get {
                return ResourceManager.GetString("ErrUnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled state {0}..
        /// </summary>
        internal static string ErrUnhandledState {
            get {
                return ResourceManager.GetString("ErrUnhandledState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type in type annotation {0}..
        /// </summary>
        internal static string ErrUnknownTypeInTypeAnnotation {
            get {
                return ResourceManager.GetString("ErrUnknownTypeInTypeAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unparseable long integer token {0}..
        /// </summary>
        internal static string ErrUnparseableIntegerToken {
            get {
                return ResourceManager.GetString("ErrUnparseableIntegerToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string constant..
        /// </summary>
        internal static string ErrUnterminatedStringConstant {
            get {
                return ResourceManager.GetString("ErrUnterminatedStringConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished loading files. {0} functions were called..
        /// </summary>
        internal static string FinishedLoadingFiles {
            get {
                return ResourceManager.GetString("FinishedLoadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused variable: {0}.
        /// </summary>
        internal static string UnusedVariable {
            get {
                return ResourceManager.GetString("UnusedVariable", resourceCulture);
            }
        }
    }
}
